auth:
  avatar: ''
  enabled: true
  password: "password"
  secret_key: "CHANGE_THIS_SECRET_KEY" # 务必修改此密钥
  username: "admin"
global:
  check_interval_minutes: 60
  external_url: "http://localhost:8000"
  log_level: INFO
  show_log_panel: true
  theme: light
monitor:
  netease:
    enabled: true
    interval: 60
    users:
    - id: '6452'
      name: 周杰伦
      avatar: ''
  qqmusic:
    enabled: true
    interval: 60
    users:
    - id: '0025NhlN2yWrP4'
      name: 周杰伦
      avatar: ''
notify:
  telegram:
    bot_token: ''
    chat_id: ''
    enabled: false
  wecom:
    agentid: ''
    corpid: ''
    corpsecret: ''
    enabled: false
    encoding_aes_key: ''
    token: ''
storage:
  auto_cache_enabled: true
  cache_dir: /audio_cache
  favorites_dir: /favorites
  library_path: ''
  retention_days: 180
